// src/app/layout.tsx
import { ClerkProvider, ClerkLoaded } from "@clerk/nextjs";
import { Metadata } from "next";
import "../styles/globals.css"; // Global styles
import "../styles/sidebar.css";
import { fonts } from "../font";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Navbar from "../../@/components/layout/navbar"; // Navbar import

const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY || "";

export const metadata: Metadata = {
  title: "Aether DApp",
  description: "Generated by create dapp",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider publishableKey={clerkPublishableKey}>
      <ClerkLoaded>
        <html lang="en">
          <body className={`${fonts.default.className} bg-teal-800 min-h-screen text-white`}>
            {/* NavBar component added at the top */}
            <div className="flex flex-col">
              <Navbar /> {/* Navbar component at the top */}
              <main className="">{children}</main> {/* Main content area */}
            </div>
            <Analytics />
            <SpeedInsights />
          </body>
        </html>
      </ClerkLoaded>
    </ClerkProvider>
  );
}
