// src/app/layout.tsx
import type { Metadata } from "next";
import '../styles/globals.css';
import { fonts } from "../font.tsx";
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${fonts.default.className} bg-cover bg-center min-h-screen`}
        style={{
          backgroundImage: 'url(https://res.cloudinary.com/dw9rtddmt/image/upload/v1722103739/Thumbnail_2_n44vq5.png)',
          fontFamily: fonts.default.className, // quicksand fontu font.tsx içinde tanımlandıysa
        }}
      >
        <main>{children}</main>
        <Analytics />
      </body>
    </html>
  );
}
